# Questão 1
Seja $A_{a,b,n}$ $\in$ $\mathbf{R}^{n\times n}$ uma matriz tri-diagonal dada por:
$$A_{a,b,n}=\begin{bmatrix}
a & b & 0 & \cdots & 0 & 0\\ 
b & a & b & \ddots & \ddots & \vdots\\ 
0 & b & a & b & \ddots & \vdots\\ 
\vdots & \ddots & \ddots & \ddots & \ddots & 0\\ 
\vdots & \ddots & \ddots & b & a & b\\ 
0 & \cdots & \cdots & 0 & b & a
\end{bmatrix}$$


#### a) Faça um algoritmo para obter uma decomposição de Cholesky de uma matriz tridiagonal, supondo que ela seja definida positiva

In [1]:
import numpy as np
import math

# Input: Matriz simetrica e positiva definida A(nxn)
# Output: Matriz de triangular inferior L, A=L^T L
def choleskyDecomposition(A):
    L = np.tril(A)
    n = np.shape(A)[0]
    for k in range(n-1):
        L[k][k] = math.sqrt(L[k][k])
        for i in range(k+1,n):
            L[i][k] /= L[k][k]
        for j in range(k+1,n):
            for i in range(j,n):
                L[i][j] -= L[i][k] * L[j][k]
    L[n-1][n-1] = math.sqrt(L[n-1][n-1])
    return L

In [2]:
A = np.matrix([[4.0,-1.0,0.0,0.0],[-1.0,4.0,-1.0,0.0],[0.0,-1.0,4.0,-1.0],[0.0,0.0,-1.0,4.0]])
print(A)
print()
L = choleskyDecomposition(A)
print(L)
print()
print(L.dot(L.T))

[[ 4. -1.  0.  0.]
 [-1.  4. -1.  0.]
 [ 0. -1.  4. -1.]
 [ 0.  0. -1.  4.]]

[[ 2.          0.          0.          0.        ]
 [-0.5         1.93649167  0.          0.        ]
 [ 0.         -0.51639778  1.93218357  0.        ]
 [ 0.          0.         -0.51754917  1.93187548]]

[[ 4. -1.  0.  0.]
 [-1.  4. -1.  0.]
 [ 0. -1.  4. -1.]
 [ 0.  0. -1.  4.]]


#### b) Faça um algoritmo para obter uma decomposição QR de uma matriz tridiagonal. Escolha entre Gram-Schmidt

No contexto de uma matriz tridiagonal onde teremos a presença de muitos elementos iguais a zero, a rotação de Givens é a melhor escolha para uma computação eficiente.

In [3]:
import numpy as np
import math

def givens(a,b):
    if b == 0:
        c = 1
        s = 0
    elif abs(b) > abs(a):
        s = 1/(math.sqrt(1+(-a/b)**2))
        c = (-a/b)*s
    else:
        c = 1/(math.sqrt(1+(-b/a)**2))
        s = (-b/a)*c
    
    return c,s

def getQ(A):
    m = np.shape(A)[0]
    n = np.shape(A)[1]
    Q = np.eye(m)
    for C in range(n-1):
        for L in range(C+1,m):
            if A.A[L][C] != 0.0:
                c,s = givens(A.A[C][C],A.A[L][C])
                for k in range(n):
                    aux1 = A.A[C][k]
                    aux2 = A.A[L][k]
                    A.A[C][k] = round( c*aux1 - s*aux2 , 5 )
                    A.A[L][k] = round( s*aux1 + c*aux2 , 5 )
                for k in range(m):
                    aux1 = Q[k][C]
                    aux2 = Q[k][L]
                    Q[k][C] = round( c*aux1 - s*aux2 , 5 )
                    Q[k][L] = round( s*aux1 + c*aux2 , 5 )
    for u in range(n,m):
        if A.A[u][n-1] != 0:
            c,s = givens(A.A[n-1][n-1],A.A[u][n-1])
            for k in range(n):
                aux1 = A.A[n-1][k]
                aux2 = A.A[u][k]
                A.A[n-1][k] = round( c*aux1 - s*aux2 , 5 )
                A.A[u][k] = round( s*aux1 + c*aux2 , 5 )
            for k in range(m):
                aux1 = Q[k][n-1]
                aux2 = Q[k][u]
                Q[k][n-1] = round( c*aux1 - s*aux2 , 5 )
                Q[k][u] = round( s*aux1 + c*aux2 , 5 )
                
    return Q

def getR(O,Q):
    return Q.T.dot(O)

In [4]:
#O = np.matrix([[2.0,3.0,],[5.0,4.0],[8.0,9.0]])
#A = np.matrix([[2.0,3.0,],[5.0,4.0],[8.0,9.0]])
O = np.matrix([[4.0,-1.0,0.0,0.0],[-1.0,4.0,-1.0,0.0],[0.0,-1.0,4.0,-1.0],[0.0,0.0,-1.0,4.0]])
A = np.matrix([[4.0,-1.0,0.0,0.0],[-1.0,4.0,-1.0,0.0],[0.0,-1.0,4.0,-1.0],[0.0,0.0,-1.0,4.0]])

print(A)
print()
Q = getQ(A)
print(Q)
print()
R = getR(O,Q)
print(R)
print()
QR = Q.dot(R)
for L in range(np.shape(QR)[0]):
    for C in range(np.shape(QR)[1]):
        QR.A[L][C] = round(QR.A[L][C],4)
print(QR)

[[ 4. -1.  0.  0.]
 [-1.  4. -1.  0.]
 [ 0. -1.  4. -1.]
 [ 0.  0. -1.  4.]]

[[ 0.97014  0.23387  0.06193  0.0172 ]
 [-0.24254  0.93544  0.24775  0.06882]
 [ 0.      -0.26504  0.92906  0.25808]
 [ 0.       0.      -0.26766  0.96351]]

[[ 4.12310000e+00 -1.94030000e+00  2.42540000e-01  0.00000000e+00]
 [ 4.00000000e-05  3.77293000e+00 -1.99560000e+00  2.65040000e-01]
 [-3.00000000e-05  1.00000000e-05  3.73615000e+00 -1.99970000e+00]
 [-2.00000000e-05  5.55111512e-17 -1.00000000e-05  3.59596000e+00]]

[[ 4. -1. -0. -0.]
 [-1.  4. -1. -0.]
 [-0. -1.  4. -1.]
 [-0. -0. -1.  4.]]


# Questão 3
Determine uma base ortonormal para o espaço complementar ortogonal ao vetor $v=[1,-1,1]$ $\in$ $\mathbf{R}^3$

In [5]:
import numpy as np
import math

#Resolver a equação v1x+v2y+v3z=0
#Tome z=y=1 e x = -v2/v1 - v3/v1
def findOrthogonalBase(v):
    v1 = np.array([-v[1]/v[0] - v[2]/v[0], 1 , 1])
    print(round(v1.dot(v),10))
    v2 = np.cross(v,v1)
    print(round(v2.dot(v),10))
    return v1,v2

def tranformOrthonormal(v1,v2):
    v1 /= np.linalg.norm(v1)
    v2 /= np.linalg.norm(v2)
    return v1,v2

In [6]:
v = np.array([1, -1 , 1])
v1,v2 = findOrthogonalBase(v)
v1,v2 = tranformOrthonormal(v1,v2)
print()
print(v1)
print()
print(v2)
print()
print(round(v1.dot(v),10))
print(round(v2.dot(v),10))


0.0
0.0

[0.         0.70710678 0.70710678]

[-0.81649658 -0.40824829  0.40824829]

0.0
0.0


# Questão 4
Calcule a pseudoinversa de A:
$$A=\begin{bmatrix}
1 & 0\\ 
0 & 1\\ 
1 & 1
\end{bmatrix}$$

In [7]:
import numpy as np
import math

def pseudoInversa(A):
    AtA = A.T.dot(A)    
    return AtA.I.dot(A.T)

In [8]:
A = np.matrix([[1.0,0.0,],[0.0,1.0],[0.0,1.0]])
print(pseudoInversa(A))

[[1.  0.  0. ]
 [0.  0.5 0.5]]
